# Generated by Django 3.2.2 on 2022-04-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention', models.TextField(default='', max_length=250)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('requestor', models.CharField(default='', max_length=100)),
                ('requestor_email', models.EmailField(default='', max_length=70)),
                ('requestor_phone', models.CharField(default='', max_length=70)),
                ('donation_amount', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(default='', max_length=100)),
                ('diocese', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.intentions')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.parishes')),
            ],
        ),
    ]
