# Generated by Django 3.2.2 on 2022-04-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220414_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
