# Generated by Django 3.2.2 on 2022-04-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220415_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentions',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='parishes',
            old_name='create',
            new_name='created',
        ),
    ]
