# Generated by Django 3.2.2 on 2022-04-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220415_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentions',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
